/* Data — trupp, formation, koherens */
window.MP_DATA = {
  match: {
    opponent: "Lerum IS",
    venue: "Aspevallen",
    home: false,
    kickoff: "I morgon · 19:00",
    competition: "Seriematch",
  },
  formation433: {
    // normerad 0–100 på grön plan (x=bredd, y=djup, 0 = vår MV)
    positions: [
      { id: "gk", label: "MV", x: 50, y: 8 },
      { id: "lb", label: "VB", x: 15, y: 28 },
      { id: "lcb", label: "VMB", x: 37, y: 22 },
      { id: "rcb", label: "HMB", x: 63, y: 22 },
      { id: "rb", label: "HB", x: 85, y: 28 },
      { id: "dm", label: "CM-6", x: 50, y: 45 },
      { id: "lcm", label: "CM-8", x: 32, y: 55 },
      { id: "rcm", label: "CM-10", x: 68, y: 55 },
      { id: "lw", label: "VY", x: 15, y: 78 },
      { id: "st", label: "FW", x: 50, y: 82 },
      { id: "rw", label: "HY", x: 85, y: 78 },
    ],
  },
  roster: [
    { n: 1, name: "Ali", role: "MV" },
    { n: 2, name: "Daniel", role: "B" },
    { n: 3, name: "Sabarr", role: "MB" },
    { n: 4, name: "Ado", role: "MB" },
    { n: 5, name: "Rayan", role: "B" },
    { n: 6, name: "Ahmed", role: "CM" },
    { n: 7, name: "Benji", role: "Y" },
    { n: 8, name: "Galvan", role: "CM" },
    { n: 9, name: "Leo", role: "FW" },
    { n: 10, name: "Yosef", role: "CM" },
    { n: 11, name: "Haris", role: "Y" },
    { n: 12, name: "Meisam", role: "MV" },
    { n: 13, name: "Pascal", role: "MB" },
    { n: 14, name: "Måns", role: "CM" },
    { n: 15, name: "Aldin", role: "Y" },
    { n: 16, name: "Maric", role: "FW" },
  ],
  matchmal: [
    "Dueller — vad betyder det att vinna en duell?",
    "Andrabollsspel — attackera bollen direkt!",
    "Tre poäng.",
    "Samma ord från målvakt till anfallare.",
    "Vinn våra 1-mot-1 i gyllene zonen.",
  ],
};

/* Koherens-sektioner (redigerbara) */
window.MP_COHERENCE = [
  {
    id: "forutsattningar",
    num: "01",
    title: "Förutsättningar",
    eyebrow: "Kontext",
    bullets: [
      "Bra trupp. Svår bortamatch.",
      "Lerum har kommit längre i sin resa — vi är underdogs.",
      "Gör en bra insats. Utgången blir vad den blir.",
    ],
  },
  {
    id: "identitet",
    num: "02",
    title: "Identitet — och varför",
    eyebrow: "Vem vi är",
    subtitle: "Första 15 sätter tonen. Om det hackar: gå tillbaka hit.",
    principles: ["Duellspel", "Andrabollsspel", "Springa i djupled"],
    bullets: [
      "Vi pressar högt och jagar åt samma håll.",
      "Vi försvarar gyllene zonen — inget skott från mitten.",
      "Vi spelar framåt så fort det är på — annars rör vi bollen tills det är på.",
    ],
    fallback: "Om det hackar: förenkla. Korta passningar. Vinn andrabollar. Bekväm press i mellanblock tills rytmen är tillbaka.",
  },
  {
    id: "forsvar",
    num: "03",
    title: "Försvarsspel",
    eyebrow: "När de har bollen",
    principles: ["Tre korridorer", "Splitta planen", "Aldrig på insidan", "Aldrig i oss"],
    bullets: [
      "Hög press på målvaktens utspel — FW stänger lång bana, Y:na på backarna.",
      "Mellanblock om de tar sig förbi — kompakt, jaga åt samma håll.",
      "Lågt block i box: hybridförsvar. Zon i boxen + två strikt man.",
    ],
  },
  {
    id: "omst-anfall",
    num: "04",
    title: "Omställning → anfall",
    eyebrow: "Vi vinner bollen",
    principles: ["Kontra först", "Annars uppbyggnad", "Fyra alternativ"],
  },
  {
    id: "anfall",
    num: "05",
    title: "Anfallsspel — den gyllene femman",
    eyebrow: "Vi har bollen",
    principles: ["Säkra kontringsläge", "Spela in", "Krossa ut", "Spring framåt", "Fyll på boxen"],
    fivePoints: [
      { k: "Spelbarhet", v: "Erbjud alltid fyra riktningar. Ingen får bli isolerad." },
      { k: "Avstånd", v: "8–12 meter mellan närmaste två. Inte för nära, inte för långt." },
      { k: "Bredd", v: "Yttre CB eller Y håller bredden — alltid någon på kanten." },
      { k: "Djup", v: "FW hotar bakom backlinjen. Ingen backlinje i fred." },
      { k: "Övertal", v: "I gyllene zonen — fem mot fyra, eller vi väntar." },
    ],
  },
  {
    id: "omst-forsvar",
    num: "06",
    title: "Omställning → försvar",
    eyebrow: "Vi tappar bollen",
    principles: ["Direkt bollåtererövring", "Indirekt bollåtererövring"],
  },
  {
    id: "fasta-forsvar",
    num: "07",
    title: "Försvar mot fasta",
    eyebrow: "Deras hörna / frispark",
    principles: ["Fyra zoner", "Övriga markering", "Diagonal utgång vid kontring"],
    note: "Adnan går igenom inför matchen. Frågor välkomna innan.",
  },
  {
    id: "fasta-anfall",
    num: "08",
    title: "Anfall från fasta",
    eyebrow: "Vår hörna / frispark",
    note: "Adnan går igenom inför matchen. Frågor välkomna innan.",
  },
  {
    id: "ovrigt",
    num: "09",
    title: "Övriga roller",
    eyebrow: "Roller & ansvar",
    roles: [
      { k: "Kapten", v: "Ado" },
      { k: "Straff", v: "Haris" },
      { k: "Frispark — inlägg", v: "Galvan" },
      { k: "Hörnor vänster", v: "Galvan" },
      { k: "Hörnor höger", v: "Haris" },
    ],
  },
];

/* Press-triggers (egna kort) */
window.MP_PRESS = [
  { trigger: "Deras vänsterback har bollen", action: "HY pressar direkt, CM-10 dubblar, VY stänger spelvänd. Vaksam — de vill anfalla på sin högerkant med ojämn symmetri." },
  { trigger: "Dålig första touch från deras CB", action: "FW pressar direkt, Y på backen, CM stänger mellan." },
  { trigger: "Målvakten får bollen tillbaka", action: "FW stänger lång bana — tvinga kort. Y:na klättrar upp." },
  { trigger: "Passning längs sidlinjen", action: "Y + B kliver mot — isolera vid linjen." },
];

/* Speluppbyggnad */
window.MP_UPPBYGGNAD = [
  { phase: "1", who: "Skapa säkerhet", what: "Hindra deras kontringsspel." },
  { phase: "2", who: "Spela in centralt", what: "Centrera dem — flytta ur yttre korridorer." },
  { phase: "3", who: "Spelvänd", what: "Ut till yttre korridor." },
  { phase: "4", who: "Spring framåt", what: "Överlappande ytterbackar." },
  { phase: "5", who: "Fyll på boxen", what: "Spelare i straffområdet." },
];

/* Taktiska situationer — platshållare per koherens-sektion */
window.MP_SITUATIONS = {
  "02-platshallare": {
    sectionId: "identitet",
    title: "Identitet — platshållare",
    variant: "green",
    players: [
      { n: 1, x: 50, y: 92 },
      { n: 2, x: 85, y: 72 },
      { n: 3, x: 63, y: 78 },
      { n: 4, x: 37, y: 78 },
      { n: 5, x: 15, y: 72 },
      { n: 6, x: 50, y: 55 },
      { n: 8, x: 32, y: 45 },
      { n: 10, x: 68, y: 45 },
      { n: 7, x: 85, y: 22 },
      { n: 9, x: 50, y: 18 },
      { n: 11, x: 15, y: 22 },
    ],
    arrows: [],
    zones: [],
    ball: null,
    bench: false,
  },
  "03-platshallare": {
    sectionId: "forsvar",
    title: "Hög press — platshållare",
    variant: "green",
    players: [
      { n: 1, x: 50, y: 92 },
      { n: 2, x: 85, y: 72 },
      { n: 3, x: 63, y: 78 },
      { n: 4, x: 37, y: 78 },
      { n: 5, x: 15, y: 72 },
      { n: 6, x: 50, y: 55 },
      { n: 8, x: 32, y: 45 },
      { n: 10, x: 68, y: 45 },
      { n: 7, x: 85, y: 22, highlight: true },
      { n: 9, x: 50, y: 18, highlight: true },
      { n: 11, x: 15, y: 22, highlight: true },
    ],
    arrows: [
      { from: [50, 18], to: [50, 8], style: "dashed", color: "gold" },
    ],
    zones: [
      { x: 25, y: 6, w: 50, h: 20, fill: "greenHighlight" },
    ],
    ball: { x: 50, y: 8 },
    bench: false,
  },
  "03-press-vb": {
    sectionId: "forsvar",
    title: "Press på deras vänsterback",
    subtitle: "Primär press-trigger — HY pressar, CM-10 dubblar.",
    variant: "green",
    players: [
      { n: 1, x: 50, y: 92 },
      { n: 2, x: 85, y: 70 },
      { n: 3, x: 63, y: 78 },
      { n: 4, x: 37, y: 78 },
      { n: 5, x: 15, y: 72 },
      { n: 6, x: 50, y: 50 },
      { n: 8, x: 30, y: 40 },
      { n: 10, x: 65, y: 35, highlight: true },
      { n: 7, x: 82, y: 20, highlight: true },
      { n: 9, x: 50, y: 18 },
      { n: 11, x: 18, y: 22 },
    ],
    arrows: [
      { from: [82, 20], to: [90, 14], style: "solid", color: "gold" },
      { from: [65, 35], to: [82, 22], style: "dashed", color: "gold" },
      { from: [18, 22], to: [45, 20], style: "dashed", color: "gold" },
    ],
    zones: [],
    ball: { x: 92, y: 12 },
    bench: false,
  },
  "04-platshallare": {
    sectionId: "omst-anfall",
    title: "Kontra i mitten — platshållare",
    variant: "green",
    players: [
      { n: 1, x: 50, y: 92 },
      { n: 2, x: 85, y: 72 },
      { n: 3, x: 63, y: 78 },
      { n: 4, x: 37, y: 78 },
      { n: 5, x: 15, y: 72 },
      { n: 6, x: 50, y: 55, highlight: true },
      { n: 8, x: 32, y: 45 },
      { n: 10, x: 68, y: 45 },
      { n: 7, x: 85, y: 22 },
      { n: 9, x: 50, y: 18 },
      { n: 11, x: 15, y: 22 },
    ],
    arrows: [
      { from: [50, 55], to: [50, 22], style: "solid", color: "gold" },
    ],
    zones: [],
    ball: { x: 50, y: 55 },
    bench: false,
  },
  "05-platshallare": {
    sectionId: "anfall",
    title: "Spela in i gyllene zonen — platshållare",
    variant: "green",
    players: [
      { n: 1, x: 50, y: 92 },
      { n: 2, x: 85, y: 60 },
      { n: 3, x: 63, y: 70 },
      { n: 4, x: 37, y: 70 },
      { n: 5, x: 15, y: 60 },
      { n: 6, x: 50, y: 50 },
      { n: 8, x: 32, y: 38 },
      { n: 10, x: 68, y: 38 },
      { n: 7, x: 85, y: 18 },
      { n: 9, x: 50, y: 14, highlight: true },
      { n: 11, x: 15, y: 18 },
    ],
    arrows: [
      { from: [32, 38], to: [50, 14], style: "solid", color: "gold" },
    ],
    zones: [
      { x: 25, y: 6, w: 50, h: 18, fill: "greenHighlight" },
    ],
    ball: { x: 32, y: 38 },
    bench: false,
  },
  "06-platshallare": {
    sectionId: "omst-forsvar",
    title: "Direkt motpress — platshållare",
    variant: "green",
    players: [
      { n: 1, x: 50, y: 92 },
      { n: 2, x: 85, y: 72 },
      { n: 3, x: 63, y: 78 },
      { n: 4, x: 37, y: 78 },
      { n: 5, x: 15, y: 72 },
      { n: 6, x: 50, y: 55, highlight: true },
      { n: 8, x: 32, y: 45, highlight: true },
      { n: 10, x: 68, y: 45, highlight: true },
      { n: 7, x: 85, y: 22 },
      { n: 9, x: 50, y: 18 },
      { n: 11, x: 15, y: 22 },
    ],
    arrows: [
      { from: [32, 45], to: [50, 50], style: "dashed", color: "gold" },
      { from: [68, 45], to: [50, 50], style: "dashed", color: "gold" },
      { from: [50, 55], to: [50, 50], style: "dashed", color: "gold" },
    ],
    zones: [],
    ball: { x: 50, y: 50 },
    bench: false,
  },
  "07-platshallare": {
    sectionId: "fasta-forsvar",
    title: "Deras hörna — platshållare",
    variant: "green",
    players: [
      { n: 1, x: 50, y: 4 },
      { n: 2, x: 28, y: 10 },
      { n: 3, x: 40, y: 6 },
      { n: 4, x: 50, y: 8 },
      { n: 5, x: 60, y: 6 },
      { n: 6, x: 72, y: 10 },
      { n: 7, x: 35, y: 16 },
      { n: 8, x: 50, y: 18, highlight: true },
      { n: 10, x: 65, y: 16, highlight: true },
      { n: 9, x: 50, y: 30 },
      { n: 11, x: 50, y: 55 },
    ],
    arrows: [],
    zones: [
      { x: 30, y: 2, w: 40, h: 18, fill: "greenHighlight" },
    ],
    ball: { x: 2, y: 2 },
    bench: false,
  },
  "08-platshallare": {
    sectionId: "fasta-anfall",
    title: "Vår hörna — platshållare",
    variant: "green",
    players: [
      { n: 1, x: 50, y: 92 },
      { n: 2, x: 35, y: 50 },
      { n: 3, x: 40, y: 14 },
      { n: 4, x: 50, y: 12 },
      { n: 5, x: 60, y: 14 },
      { n: 6, x: 70, y: 16 },
      { n: 7, x: 50, y: 22 },
      { n: 8, x: 30, y: 22 },
      { n: 9, x: 30, y: 10 },
      { n: 10, x: 50, y: 40 },
      { n: 11, x: 2, y: 2, highlight: true },
    ],
    arrows: [
      { from: [2, 2], to: [50, 12], style: "solid", color: "gold" },
    ],
    zones: [],
    ball: { x: 2, y: 2 },
    bench: false,
  },
};
